version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /android
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /ios
    schedule:
      interval: daily
