---
name: Code Metrics check

env:
  flutter-version: ${{ env.FLUTTER_VERSION }}
  channel: ${{ env.FLUTTER_CHANNEL }}

on:
  - pull_request:
      types: [opened, synchronize]

jobs:
  dart-code-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: "android, bin, fastlane, ios, lib"
          pull_request_comment: true
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: true
          check_unused_files_folders: "android, bin, fastlane, ios, lib"
