on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**.dart'
      - '**/pubspec.*'
      - '*.yaml'
      - assets/**
      - .fvm/fvm_config.json

name: Code checks workflow

concurrency:
  group: qa-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.added-and-modified-files.outputs.all }}
      changed_dart_files: ${{ steps.added-and-modified-files.outputs.dart }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@039afcd1024c210363c9d3fc8fd07e1f3fcf2867 # v35.9.3
        with:
          files: |
            **/*.dart
            **/pubspec.yaml
          files_ignore: |
            **/*.g.dart
            **/*.freezed.dart
            **/*.mocks.dart

      - id: added-and-modified-files
        name: Get all added and modified files
        run: |
          changed_files=$(echo "${{ steps.changed-files.outputs.added_files }} ${{ steps.changed-files.outputs.modified_files }}" | xargs)
          changed_dart_files=$(echo "$changed_files" | tr ' ' '\n' | grep -E '\.dart$' | xargs)

          echo "all=$changed_files" >> $GITHUB_OUTPUT
          echo "dart=$changed_dart_files" >> $GITHUB_OUTPUT

  lint:
    name: Run lint on affected files
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.changed_files }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@6ffa30473b346f7d7c63cf9e03e6a886f940a72b # v1.2.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Analyze code
        if: ${{ needs.check-changes.outputs.changed_files }}
        run: |
          dart analyze --fatal-warnings \
            ${{ needs.check-changes.outputs.changed_files }}

      - name: Check code formatting
        if: ${{ always() && needs.check-changes.outputs.changed_dart_files }}
        run: |
          flutter format --output=none --set-exit-if-changed \
            ${{ needs.check-changes.outputs.changed_dart_files }}

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@6ffa30473b346f7d7c63cf9e03e6a886f940a72b # v1.2.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Options
        run: |
          tee lib/firebase_options.dart <<EOF
          class DefaultFirebaseOptions {
            static const currentPlatform = null;
          }
          EOF

      - name: Run unit tests
        run: flutter test --timeout=1h --dart-define=isCI=true --coverage

      - name: Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          file: ./coverage/lcov.info
