name: "Distribute Android Flutter app"

on:
  workflow_call:
    inputs:
      environment:
        description: "Distribution environment"
        type: string
        required: true

    secrets:
      PENHAS_BASE_URL:
        required: true
      ANDROID_BUILD_FILES:
        required: true
      FIREBASE_TOKEN:
        required: false
      GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64:
        required: true
      TESTER_EMAIL:
        required: false

jobs:
  distribute:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
        with:
          java-version: 11
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc # v2.0.10

      - name: Retrieve Flutter version from FVM config
        uses: kuhnroyal/flutter-fvm-config-action@6ffa30473b346f7d7c63cf9e03e6a886f940a72b # v1.2.0

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Install Ruby to use Fastlane
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./android

      - name: Get config files
        run: base64 -d <<< "${{ secrets.ANDROID_BUILD_FILES }}" | tar xzf -

      - name: Get Google Account credentials
        run: base64 -d <<< "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_B64 }}" > $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_PATH
        env:
          GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_PATH: ${{ runner.temp }}/play-store-api-key.json

      - name: Run lane to distribute
        uses: maierj/fastlane-action@516faaa1c6c7b366ecd238b4e4608d286874dd94 # v3.0.0
        with:
          lane: ${{ vars.TARGET_LANE }}
          options: '{ "tester_email": "${{ secrets.TESTER_EMAIL }}" }'
          subdirectory: ./android
        env:
          FASTLANE_SKIP_UPDATE_CHECK: true
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_CREDENTIAL_PATH: ${{ runner.temp }}/play-store-api-key.json
          IOS_BUNDLE_ID: ${{ vars.IOS_BUNDLE_ID }}
          PENHAS_BASE_URL: ${{ secrets.PENHAS_BASE_URL }}
